FROM docker.io/alpine:3.16

COPY artifacts /artifacts

RUN cp /artifacts/$(cat /etc/apk/arch)-unknown-linux-musl/bin/nk /usr/local/bin/nk && \
	rm -r /artifacts

ENV NK_DATA_DIR=/nk

RUN mkdir /nk && \
	for i in $(nk toolbox list); do \
		ln -sv nk "/usr/local/bin/$i" || exit 1; \
	done
